### ISSUE TITLE
Error while importing CSV

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/Mail-for-Good#149]
This is the error : 

```
14:08:49 0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
14:08:49 0|index    | TypeError: Cannot read property 'isNewRecord' of undefined
14:08:49 0|index    |     at Promise.all.then.values (/home/karuppiah/FOSS/Mail-for-Good/server/controllers/list/import-csv.js:71:44)
14:08:49 0|index    |     at tryCatcher (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/util.js:16:23)
14:08:49 0|index    |     at Promise._settlePromiseFromHandler (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:512:31)
14:08:49 0|index    |     at Promise._settlePromise (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:569:18)
14:08:49 0|index    |     at Promise._settlePromise0 (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:614:10)
14:08:49 0|index    |     at Promise._settlePromises (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:693:18)
14:08:49 0|index    |     at Promise._fulfill (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:638:18)
14:08:49 0|index    |     at PromiseArray._resolve (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise_array.js:126:19)
14:08:49 0|index    |     at PromiseArray._promiseFulfilled (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise_array.js:144:14)
14:08:49 0|index    |     at Promise._settlePromise (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:574:26)
14:08:49 0|index    |     at Promise._settlePromise0 (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:614:10)
14:08:49 0|index    |     at Promise._settlePromises (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:693:18)
14:08:49 0|index    |     at Async._drainQueue (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:133:16)
14:08:49 0|index    |     at Async._drainQueues (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:143:10)
14:08:49 0|index    |     at Immediate.Async.drainQueues (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:17:14)
14:08:49 0|index    |     at runCallback (timers.js:672:20)
14:08:49 0|index    |     at tryOnImmediate (timers.js:645:5)
14:08:49 0|index    |     at processImmediate [as _immediateCallback] (timers.js:617:5)
14:10:49 0|index    | Unhandled rejection TypeError: Cannot read property 'isNewRecord' of undefined
14:10:49 0|index    |     at Promise.all.then.values (/home/karuppiah/FOSS/Mail-for-Good/server/controllers/list/import-csv.js:71:44)
14:10:49 0|index    |     at tryCatcher (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/util.js:16:23)
14:10:49 0|index    |     at Promise._settlePromiseFromHandler (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:512:31)
14:10:49 0|index    |     at Promise._settlePromise (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:569:18)
14:10:49 0|index    |     at Promise._settlePromise0 (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:614:10)
14:10:49 0|index    |     at Promise._settlePromises (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:693:18)
14:10:49 0|index    |     at Promise._fulfill (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:638:18)
14:10:49 0|index    |     at PromiseArray._resolve (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise_array.js:126:19)
14:10:49 0|index    |     at PromiseArray._promiseFulfilled (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise_array.js:144:14)
14:10:49 0|index    |     at Promise._settlePromise (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:574:26)
14:10:49 0|index    |     at Promise._settlePromise0 (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:614:10)
14:10:49 0|index    |     at Promise._settlePromises (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/promise.js:693:18)
14:10:49 0|index    |     at Async._drainQueue (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:133:16)
14:10:49 0|index    |     at Async._drainQueues (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:143:10)
14:10:49 0|index    |     at Immediate.Async.drainQueues (/home/karuppiah/FOSS/Mail-for-Good/node_modules/bluebird/js/release/async.js:17:14)
14:10:49 0|index    |     at runCallback (timers.js:672:20)
14:10:49 0|index    |     at tryOnImmediate (timers.js:645:5)
14:10:49 0|index    |     at processImmediate [as _immediateCallback] (timers.js:617:5)

```

And when I logged the `listInstance` variable which I found at [this line](https://github.com/freeCodeCamp/Mail-for-Good/blob/master/server/controllers/list/import-csv.js#L71), I realized that there is only a `_options` key in it and no `$options` key. I think this is all due to the recent update in the packages. I guess the `pg` postgres package ? Not sure. So I changed [this line](https://github.com/freeCodeCamp/Mail-for-Good/blob/master/server/controllers/list/import-csv.js#L71) to this :

```
const listIsNew = listInstance._options.isNewRecord;
```

and tried again, and this time, it showed the list is created, but it wasn't able to show the list subscribers when the notification was clicked and the list didn't show up in the manage lists page. But it was present in the `lists` postgres table, with `ready` as `status`, unlike before (it was due to `$options` bug and had `processing` as the `status`) and `total` column was 0 indicating 0 subscribers. And the list subscribers weren't obtained and displayed as it still had some problems in putting the records in the `listsubscribers` table with the proper `listId`. I could see mails that I imported as records in `listsubscribers`, but none of them had `listId`, so there were bugs due to that

**Comment by karuppiah7890** [comment]
Solved in #152
