### ISSUE TITLE
Development Setup Issue

### ISSUE THREAD

**Issue by ZaynMalloc** [freeCodeCamp/Mail-for-Good#154]
I get SequelizeDatabaseError when I run npm run dev and npm run start.

```
zach@zach-VirtualBox:~/Documents/Code/Mail-for-Good$ npm run dev

> nonprofit-email-service@1.0.0 dev /home/zach/Documents/Code/Mail-for-Good
> DEV_SEND_RATE=200 NODE_ENV=development node --harmony-async-await server/index.js

Clickthrough tracking: Make sure that geoip data has been downloaded: 
   $ cd node_modules/geoip-lite
   $ npm run-script updatedb

  ############################
  #   Mail 4 Good started    #
  ############################
  # Port: 8080
  ############################
  
(node:10691) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
Unhandled rejection SequelizeDatabaseError: relation "users" does not exist
    at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
    at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:96:13)
    at Result.emit (events.js:191:7)
    at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
    at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at Query.run (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:79:12)
    at retry (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:529:32)
    at /home/zach/Documents/Code/Mail-for-Good/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/home/zach/Documents/Code/Mail-for-Good/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:529:14)
From previous event:
    at Sequelize.query (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:526:8)
    at QueryInterface.select (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/query-interface.js:671:27)
    at Promise.try.then.then.then (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/model.js:1538:34)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Function.findAll (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/model.js:1535:8)
    at module.exports (/home/zach/Documents/Code/Mail-for-Good/server/restore-db-state.js:16:15)
    at Object.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/server/index.js:91:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
An error occurred while creating the table: { SequelizeDatabaseError: column "listsubscriberId" does not exist
    at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
    at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:96:13)
    at Result.emit (events.js:191:7)
    at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
    at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at Query.run (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:79:12)
    at retry (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:529:32)
    at /home/zach/Documents/Code/Mail-for-Good/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/home/zach/Documents/Code/Mail-for-Good/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:529:14)
From previous event:
    at Sequelize.query (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:526:8)
    at QueryInterface.addIndex (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/query-interface.js:427:27)
    at Promise.map.index (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/model.js:1140:64)
From previous event:
    at Promise.try.then.then.then.then.then.indexes (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/model.js:1140:22)
From previous event:
    at Function.sync (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/model.js:1124:6)
    at Promise.each.model (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:690:50)
From previous event:
    at Promise.try.then.then (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:690:22)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Sequelize.sync (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/sequelize.js:677:8)
    at Object.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/server/models/index.js:37:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/server/restore-db-state.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/server/index.js:13:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
  name: 'SequelizeDatabaseError',
  parent: 
   { error: column "listsubscriberId" does not exist
       at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:561:20)
     name: 'error',
     length: 106,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'indexcmds.c',
     line: '1055',
     routine: 'ComputeIndexAttrs',
     sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
  original: 
   { error: column "listsubscriberId" does not exist
       at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:561:20)
     name: 'error',
     length: 106,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'indexcmds.c',
     line: '1055',
     routine: 'ComputeIndexAttrs',
     sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
  sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' }
webpack built 87e5928f3103516f55ef in 17701ms
Hash: 87e5928f3103516f55ef
Version: webpack 2.6.1
Time: 17701ms
                                 Asset       Size  Chunks                    Chunk Names
  e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]         
  f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]         
  4c31cd6e67691825fb51fcacef8956c7.ico    1.15 kB          [emitted]         
  7f690e503a254e0b8349aec0177e07aa.ttf     120 kB          [emitted]         
  7799dece2c79854f63f09e7dfa528b88.jpg     124 kB          [emitted]         
  89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]         
  e44520ab9079ea7633bfa874bed5d21d.eot    5.82 kB          [emitted]         
 fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]         
448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]         
  a770b6797b68e3f8920e473eb824bac0.gif    23.3 kB          [emitted]         
                             bundle.js    7.91 MB       0  [emitted]  [big]  app
                            index.html  863 bytes          [emitted]         
chunk    {0} bundle.js (app) 6.76 MB [entry] [rendered]
   [12] (webpack)/buildin/module.js 517 bytes {0} [built]
  [736] ./client/index.js 1.67 kB {0} [built]
  [737] (webpack)-hot-middleware/client.js?reload=true 6.73 kB {0} [built]
  [943] ./~/bootstrap/dist/js/bootstrap.min.js 37 kB {0} [built]
  [987] ./client/favicon.ico 82 bytes {0} [built]
 [1229] ./~/path-browserify/index.js 6.18 kB {0} [built]
 [1235] ./~/querystring-es3/index.js 127 bytes {0} [built]
 [1588] ./~/strip-ansi/index.js 161 bytes {0} [built]
 [1590] ./client/styles/index.scss 1.15 kB {0} [built]
 [1591] ./client/utils/adminLte/mail-for-good-theme.css 1.21 kB {0} [built]
 [1592] ./~/admin-lte/dist/css/AdminLTE.min.css 1.1 kB {0} [built]
 [1593] ./~/bootstrap/dist/css/bootstrap.min.css 1.1 kB {0} [built]
 [1594] ./~/react-bootstrap-table/dist/react-bootstrap-table.min.css 1.12 kB {0} [built]
 [1615] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
 [1620] multi ./index webpack-hot-middleware/client?reload=true 40 bytes {0} [built]
     + 1606 hidden modules
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  587 kB       0  
    chunk    {0} index.html 543 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./client/index.ejs 1.91 kB {0} [built]
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Compiled successfully.


```
```

zach@zach-VirtualBox:~/Documents/Code/Mail-for-Good$ npm run start

> nonprofit-email-service@1.0.0 start /home/zach/Documents/Code/Mail-for-Good
> NODE_ENV=production ./node_modules/pm2/bin/pm2 start server/index.js --node-args="--harmony-async-await" server/feedback-consumer/consumer.js --no-daemon

pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2017-07-04 02:46:50: Launching in no daemon mode
2017-07-04 02:46:50: [PM2] Starting /home/zach/Documents/Code/Mail-for-Good/server/index.js in fork_mode (1 instance)
2017-07-04 02:46:50: Starting execution sequence in -fork mode- for app name:index id:0
2017-07-04 02:46:50: App name:index id:0 online
2017-07-04 02:46:50: [PM2] Done.
2017-07-04 02:46:50: [PM2] Starting /home/zach/Documents/Code/Mail-for-Good/server/feedback-consumer/consumer.js in fork_mode (1 instance)
2017-07-04 02:46:50: Starting execution sequence in -fork mode- for app name:consumer id:1
2017-07-04 02:46:50: App name:consumer id:1 online
2017-07-04 02:46:51: [PM2] Done.
2017-07-04 02:46:51: ┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ consumer │ 1  │ fork │ 10837 │ online │ 0       │ 0s     │ 0%  │ 22.5 MB   │ disabled │
│ index    │ 0  │ fork │ 10822 │ online │ 0       │ 0s     │ 5%  │ 26.7 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
2017-07-04 02:46:51:  Use `pm2 show <id|name>` to get more details about an app
2017-07-04 02:46:51: [--no-daemon] Continue to stream logs
2017-07-04 02:46:51: [--no-daemon] Exit on target PM2 exit pid=10812
2017-07-04 02:46:51: [STREAMING] Now streaming realtime logs for [all] processes
02:46:52 1|consumer | Feedback consumer started: watching for feedback messages (bounces, complaints, etc) from SQS
02:46:52 1|consumer | (node:10837) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
02:46:52 1|consumer | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
02:46:52 1|consumer | SequelizeDatabaseError: relation "settings" does not exist
02:46:52 1|consumer |     at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
02:46:52 1|consumer |     at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Result.emit (events.js:191:7)
02:46:52 1|consumer |     at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
02:46:52 1|consumer |     at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Connection.emit (events.js:191:7)
02:46:52 1|consumer |     at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Socket.emit (events.js:191:7)
02:46:52 1|consumer |     at readableAddChunk (_stream_readable.js:178:18)
02:46:52 1|consumer |     at Socket.Readable.push (_stream_readable.js:136:10)
02:46:52 1|consumer |     at TCP.onread (net.js:561:20)
02:46:52 1|consumer | An error occurred while creating the table: { SequelizeDatabaseError: column "listsubscriberId" does not exist
02:46:52 1|consumer |     at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
02:46:52 1|consumer |     at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Result.emit (events.js:191:7)
02:46:52 1|consumer |     at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
02:46:52 1|consumer |     at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Connection.emit (events.js:191:7)
02:46:52 1|consumer |     at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
02:46:52 1|consumer |     at emitOne (events.js:96:13)
02:46:52 1|consumer |     at Socket.emit (events.js:191:7)
02:46:52 1|consumer |     at readableAddChunk (_stream_readable.js:178:18)
02:46:52 1|consumer |     at Socket.Readable.push (_stream_readable.js:136:10)
02:46:52 1|consumer |     at TCP.onread (net.js:561:20)
02:46:52 1|consumer |   name: 'SequelizeDatabaseError',
02:46:52 1|consumer |   parent: 
02:46:52 1|consumer |    { error: column "listsubscriberId" does not exist
02:46:52 1|consumer |        at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
02:46:52 1|consumer |        at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
02:46:52 1|consumer |        at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
02:46:52 1|consumer |        at emitOne (events.js:96:13)
02:46:52 1|consumer |        at Socket.emit (events.js:191:7)
02:46:52 1|consumer |        at readableAddChunk (_stream_readable.js:178:18)
02:46:52 1|consumer |        at Socket.Readable.push (_stream_readable.js:136:10)
02:46:52 1|consumer |        at TCP.onread (net.js:561:20)
02:46:52 1|consumer |      name: 'error',
02:46:52 1|consumer |      length: 106,
02:46:52 1|consumer |      severity: 'ERROR',
02:46:52 1|consumer |      code: '42703',
02:46:52 1|consumer |      detail: undefined,
02:46:52 1|consumer |      hint: undefined,
02:46:52 1|consumer |      position: undefined,
02:46:52 1|consumer |      internalPosition: undefined,
02:46:52 1|consumer |      internalQuery: undefined,
02:46:52 1|consumer |      where: undefined,
02:46:52 1|consumer |      schema: undefined,
02:46:52 1|consumer |      table: undefined,
02:46:52 1|consumer |      column: undefined,
02:46:52 1|consumer |      dataType: undefined,
02:46:52 1|consumer |      constraint: undefined,
02:46:52 1|consumer |      file: 'indexcmds.c',
02:46:52 1|consumer |      line: '1055',
02:46:52 1|consumer |      routine: 'ComputeIndexAttrs',
02:46:52 1|consumer |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
02:46:52 1|consumer |   original: 
02:46:52 1|consumer |    { error: column "listsubscriberId" does not exist
02:46:52 1|consumer |        at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
02:46:52 1|consumer |        at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
02:46:52 1|consumer |        at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
02:46:52 1|consumer |        at emitOne (events.js:96:13)
02:46:52 1|consumer |        at Socket.emit (events.js:191:7)
02:46:52 1|consumer |        at readableAddChunk (_stream_readable.js:178:18)
02:46:52 1|consumer |        at Socket.Readable.push (_stream_readable.js:136:10)
02:46:52 1|consumer |        at TCP.onread (net.js:561:20)
02:46:52 1|consumer |      name: 'error',
02:46:52 1|consumer |      length: 106,
02:46:52 1|consumer |      severity: 'ERROR',
02:46:52 1|consumer |      code: '42703',
02:46:52 1|consumer |      detail: undefined,
02:46:52 1|consumer |      hint: undefined,
02:46:52 1|consumer |      position: undefined,
02:46:52 1|consumer |      internalPosition: undefined,
02:46:52 1|consumer |      internalQuery: undefined,
02:46:52 1|consumer |      where: undefined,
02:46:52 1|consumer |      schema: undefined,
02:46:52 1|consumer |      table: undefined,
02:46:52 1|consumer |      column: undefined,
02:46:52 1|consumer |      dataType: undefined,
02:46:52 1|consumer |      constraint: undefined,
02:46:52 1|consumer |      file: 'indexcmds.c',
02:46:52 1|consumer |      line: '1055',
02:46:52 1|consumer |      routine: 'ComputeIndexAttrs',
02:46:52 1|consumer |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
02:46:52 1|consumer |   sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' }
02:46:52 0|index    | Clickthrough tracking: Make sure that geoip data has been downloaded: 
02:46:52 0|index    |    $ cd node_modules/geoip-lite
02:46:52 0|index    |    $ npm run-script updatedb
02:46:53 0|index    |   ############################
02:46:53 0|index    |   #   Mail 4 Good started    #
02:46:53 0|index    |   ############################
02:46:53 0|index    |   # Port: 8080
02:46:53 0|index    |   ############################
02:46:53 0|index    |   
02:46:53 0|index    | (node:10822) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
02:46:53 0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
02:46:53 0|index    | SequelizeDatabaseError: relation "users" does not exist
02:46:53 0|index    |     at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
02:46:53 0|index    |     at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Result.emit (events.js:191:7)
02:46:53 0|index    |     at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
02:46:53 0|index    |     at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Connection.emit (events.js:191:7)
02:46:53 0|index    |     at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Socket.emit (events.js:191:7)
02:46:53 0|index    |     at readableAddChunk (_stream_readable.js:178:18)
02:46:53 0|index    |     at Socket.Readable.push (_stream_readable.js:136:10)
02:46:53 0|index    |     at TCP.onread (net.js:561:20)
02:46:53 0|index    | An error occurred while creating the table: { SequelizeDatabaseError: column "listsubscriberId" does not exist
02:46:53 0|index    |     at Query.formatError (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
02:46:53 0|index    |     at Result.query.on.err (/home/zach/Documents/Code/Mail-for-Good/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Result.emit (events.js:191:7)
02:46:53 0|index    |     at Result.Query.handleError (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/query.js:163:8)
02:46:53 0|index    |     at Client.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/client.js:188:26)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Connection.emit (events.js:191:7)
02:46:53 0|index    |     at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:133:12)
02:46:53 0|index    |     at emitOne (events.js:96:13)
02:46:53 0|index    |     at Socket.emit (events.js:191:7)
02:46:53 0|index    |     at readableAddChunk (_stream_readable.js:178:18)
02:46:53 0|index    |     at Socket.Readable.push (_stream_readable.js:136:10)
02:46:53 0|index    |     at TCP.onread (net.js:561:20)
02:46:53 0|index    |   name: 'SequelizeDatabaseError',
02:46:53 0|index    |   parent: 
02:46:53 0|index    |    { error: column "listsubscriberId" does not exist
02:46:53 0|index    |        at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
02:46:53 0|index    |        at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
02:46:53 0|index    |        at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
02:46:53 0|index    |        at emitOne (events.js:96:13)
02:46:53 0|index    |        at Socket.emit (events.js:191:7)
02:46:53 0|index    |        at readableAddChunk (_stream_readable.js:178:18)
02:46:53 0|index    |        at Socket.Readable.push (_stream_readable.js:136:10)
02:46:53 0|index    |        at TCP.onread (net.js:561:20)
02:46:53 0|index    |      name: 'error',
02:46:53 0|index    |      length: 106,
02:46:53 0|index    |      severity: 'ERROR',
02:46:53 0|index    |      code: '42703',
02:46:53 0|index    |      detail: undefined,
02:46:53 0|index    |      hint: undefined,
02:46:53 0|index    |      position: undefined,
02:46:53 0|index    |      internalPosition: undefined,
02:46:53 0|index    |      internalQuery: undefined,
02:46:53 0|index    |      where: undefined,
02:46:53 0|index    |      schema: undefined,
02:46:53 0|index    |      table: undefined,
02:46:53 0|index    |      column: undefined,
02:46:53 0|index    |      dataType: undefined,
02:46:53 0|index    |      constraint: undefined,
02:46:53 0|index    |      file: 'indexcmds.c',
02:46:53 0|index    |      line: '1055',
02:46:53 0|index    |      routine: 'ComputeIndexAttrs',
02:46:53 0|index    |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
02:46:53 0|index    |   original: 
02:46:53 0|index    |    { error: column "listsubscriberId" does not exist
02:46:53 0|index    |        at Connection.parseE (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:567:11)
02:46:53 0|index    |        at Connection.parseMessage (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:391:17)
02:46:53 0|index    |        at Socket.<anonymous> (/home/zach/Documents/Code/Mail-for-Good/node_modules/pg/lib/connection.js:129:22)
02:46:53 0|index    |        at emitOne (events.js:96:13)
02:46:53 0|index    |        at Socket.emit (events.js:191:7)
02:46:53 0|index    |        at readableAddChunk (_stream_readable.js:178:18)
02:46:53 0|index    |        at Socket.Readable.push (_stream_readable.js:136:10)
02:46:53 0|index    |        at TCP.onread (net.js:561:20)
02:46:53 0|index    |      name: 'error',
02:46:53 0|index    |      length: 106,
02:46:53 0|index    |      severity: 'ERROR',
02:46:53 0|index    |      code: '42703',
02:46:53 0|index    |      detail: undefined,
02:46:53 0|index    |      hint: undefined,
02:46:53 0|index    |      position: undefined,
02:46:53 0|index    |      internalPosition: undefined,
02:46:53 0|index    |      internalQuery: undefined,
02:46:53 0|index    |      where: undefined,
02:46:53 0|index    |      schema: undefined,
02:46:53 0|index    |      table: undefined,
02:46:53 0|index    |      column: undefined,
02:46:53 0|index    |      dataType: undefined,
02:46:53 0|index    |      constraint: undefined,
02:46:53 0|index    |      file: 'indexcmds.c',
02:46:53 0|index    |      line: '1055',
02:46:53 0|index    |      routine: 'ComputeIndexAttrs',
02:46:53 0|index    |      sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' },
02:46:53 0|index    |   sql: 'CREATE INDEX "campaignsubscribers_listsubscriber_id" ON "campaignsubscribers" ("listsubscriberId")' }


```

**Comment by AndrewGHC** [comment]
Hey - I've fixed this (I believe). If it doesn't work (using the version I'll soon push), please let me know. Should this happen, go to /server/models/index.js and change line 37 to force: true. Start the app, then change force back to false. I'm working on a better solution to this.
