### ISSUE TITLE
Implementation of AWS SNS Queue causes an error when updating settings.

### ISSUE THREAD

**Issue by AndrewGHC** [freeCodeCamp/mail-for-good#159]
Updating any of the following fields (after settings have first been set) causes an issue with SNS.

        accessKey: settings.amazonSimpleEmailServiceAccessKey,
        secretKey: settings.amazonSimpleEmailServiceSecretKey,
        region: settings.region,
        email: settings.email

Settings are still updated, but we should delete or update the old queue first to ensure this isn't thrown. 

```
{ QueueAlreadyExists: A queue already exists with the same name and a different value for attribute DelaySeconds
    at Request.extractError (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/root1/Desktop/other/nonprofit-email-service/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'A queue already exists with the same name and a different value for attribute DelaySeconds',
  code: 'QueueAlreadyExists',
  time: 2017-07-13T00:24:11.804Z,
  requestId: 'd9159551-f3be-5883-be8d-c4b14c5593f0',
  statusCode: 400,
  retryable: false,
  retryDelay: 31.90656214508958 }
```

**Comment by AndrewGHC** [comment]
This was because one of the attributes of my own SQS queue was different to recent values. It should work fine.
