### ISSUE TITLE
docker-compose up throws errors and app doesn't start

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#163]
This looks similar to #153 . But the logs aren't exactly the same.

Here's the log : 
```
Creating mailforgood_redis_1
Creating mailforgood_postgres_1
Creating mailforgood_app_1
Attaching to mailforgood_redis_1, mailforgood_postgres_1, mailforgood_app_1
redis_1     | 1:C 16 Jul 04:06:35.911 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
redis_1     |                 _._                                                  
redis_1     |            _.-``__ ''-._                                             
redis_1     |       _.-``    `.  `_.  ''-._           Redis 3.2.9 (00000000/0) 64 bit
redis_1     |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1     |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1     |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1     |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1     |   `-._    `-._  `-./  _.-'    _.-'                                   
postgres_1  | 
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1     |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1     |  |    `-._`-._        _.-'_.-'    |                                  
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1     |       `-._    `-.__.-'    _.-'                                       
redis_1     |           `-._        _.-'                                           
postgres_1  | creating subdirectories ... ok
redis_1     |               `-.__.-'                                               
redis_1     | 
redis_1     | 1:M 16 Jul 04:06:35.912 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 16 Jul 04:06:35.912 # Server started, Redis version 3.2.9
postgres_1  | selecting default max_connections ... 100
redis_1     | 1:M 16 Jul 04:06:35.912 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 16 Jul 04:06:35.912 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 16 Jul 04:06:35.912 * The server is now ready to accept connections on port 6379
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@4.2.0
app_1       | npm info using node@v7.10.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start: nonprofit-email-service@1.0.0
app_1       | 
app_1       | > nonprofit-email-service@1.0.0 start /usr/src/app
app_1       | > NODE_ENV=production ./node_modules/pm2/bin/pm2 start server/index.js --node-args=server/feedback-consumer/consumer.js --no-daemon
app_1       | 
app_1       | 
app_1       |                         -------------
app_1       | 
app_1       | __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
app_1       |  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
app_1       |   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
app_1       |    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
app_1       |     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
app_1       |      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
app_1       |       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
app_1       |        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
app_1       |         _\///______________\///______________\///__\///////////////__
app_1       | 
app_1       | 
app_1       |          Welcome to most Advanced Process Manager for Node.js
app_1       | 
app_1       |                           Monitoring
app_1       |                         $ pm2 monitor
app_1       | 
app_1       |                       Start PM2 at boot
app_1       |                         $ pm2 startup
app_1       | 
app_1       |                      Increase Performance
app_1       |                     $ pm2 start api.js -i 4
app_1       | 
app_1       |                         -------------
app_1       | 
app_1       | pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
postgres_1  | performing post-bootstrap initialization ... ok
app_1       | 2017-07-16 04:06:38: Launching in no daemon mode
app_1       | 2017-07-16 04:06:38: [PM2] Starting /usr/src/app/server/index.js in fork_mode (1 instance)
app_1       | 2017-07-16 04:06:38: Starting execution sequence in -fork mode- for app name:index id:0
app_1       | 2017-07-16 04:06:38: App name:index id:0 online
app_1       | 2017-07-16 04:06:39: [PM2] Done.
app_1       | 2017-07-16 04:06:39: ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
app_1       | │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ watching │
app_1       | ├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
app_1       | │ index    │ 0  │ fork │ 27  │ online │ 0       │ 0s     │ 5%  │ 25.2 MB   │ disabled │
app_1       | └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
app_1       | 2017-07-16 04:06:39:  Use `pm2 show <id|name>` to get more details about an app
app_1       | 2017-07-16 04:06:39: [--no-daemon] Continue to stream logs
app_1       | 2017-07-16 04:06:39: [--no-daemon] Exit on target PM2 exit pid=17
app_1       | 2017-07-16 04:06:39: [STREAMING] Now streaming realtime logs for [all] processes
postgres_1  | syncing data to disk ... 
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | ok
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | ****************************************************
postgres_1  | WARNING: No password has been set for the database.
postgres_1  |          This will allow anyone with access to the
postgres_1  |          Postgres port to access your database. In
postgres_1  |          Docker's default configuration, this is
postgres_1  |          effectively any other container on the same
postgres_1  |          system.
postgres_1  | 
postgres_1  |          Use "-e POSTGRES_PASSWORD=password" to set
postgres_1  |          it in "docker run".
postgres_1  | ****************************************************
postgres_1  | waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
postgres_1  | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
app_1       | 04:06:39 0|index    | Feedback consumer started: watching for feedback messages (bounces, complaints, etc) from SQS
app_1       | 04:06:39 0|index    | Unhandled rejection SequelizeBaseError: connect ECONNREFUSED 172.17.0.3:5432
app_1       | 04:06:39 0|index    |     at /usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:98:20
app_1       | 04:06:39 0|index    |     at Client.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:203:5)
app_1       | 04:06:39 0|index    |     at emitOne (events.js:96:13)
app_1       | 04:06:39 0|index    |     at Connection.emit (events.js:191:7)
app_1       | 04:06:39 0|index    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:86:10)
app_1       | 04:06:39 0|index    |     at emitOne (events.js:96:13)
app_1       | 04:06:39 0|index    |     at Socket.emit (events.js:191:7)
app_1       | 04:06:39 0|index    |     at emitErrorNT (net.js:1279:8)
app_1       | 04:06:39 0|index    |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
app_1       | 04:06:39 0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
postgres_1  | LOG:  database system was shut down at 2017-07-16 04:06:38 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
postgres_1  |  done
postgres_1  | server started
postgres_1  | ALTER ROLE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | waiting for server to shut down...LOG:  autovacuum launcher shutting down
postgres_1  | .LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | LOG:  database system was shut down at 2017-07-16 04:06:41 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started

```

And the app doesn't start, as in, I am not able to `http://127.0.0.1:8080`

**Comment by AndrewGHC** [comment]
Looking into this, seems the project at Docker Hub is not updating https://hub.docker.com/r/freecodecamp/mail-for-good/.

**Comment by karuppiah7890** [comment]
@AndrewGHC Oh
