### ISSUE TITLE
sudo docker-compose up failed on local development.

### ISSUE THREAD

**Issue by darkrubyist** [freeCodeCamp/mail-for-good#274]
Hello, I was trying Mail For Good on my local development but I receive the following error.
Is there anything I can do to fix it?

Thank you! 

```
arkloves-MacBook-Pro% sudo docker-compose up
Password: ********
mailforgood_redis_1 is up-to-date
mailforgood_postgres_1 is up-to-date
Starting mailforgood_app_1 ... done
Attaching to mailforgood_redis_1, mailforgood_postgres_1, mailforgood_app_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
redis_1     | 1:C 14 Mar 02:02:10.660 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
postgres_1  | selecting default max_connections ... 100
redis_1     | 1:C 14 Mar 02:02:10.667 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
postgres_1  | selecting default shared_buffers ... 128MB
redis_1     | 1:C 14 Mar 02:02:10.667 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1  | selecting dynamic shared memory implementation ... posix
redis_1     | 1:M 14 Mar 02:02:10.671 * Running mode=standalone, port=6379.
postgres_1  | creating configuration files ... ok
redis_1     | 1:M 14 Mar 02:02:10.671 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
postgres_1  | running bootstrap script ... ok
redis_1     | 1:M 14 Mar 02:02:10.671 # Server initialized
postgres_1  | performing post-bootstrap initialization ... ok
redis_1     | 1:M 14 Mar 02:02:10.674 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
postgres_1  | syncing data to disk ... ok
redis_1     | 1:M 14 Mar 02:02:10.674 * Ready to accept connections
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  | ****************************************************
postgres_1  | WARNING: No password has been set for the database.
postgres_1  |          This will allow anyone with access to the
postgres_1  |          Postgres port to access your database. In
postgres_1  |          Docker's default configuration, this is
postgres_1  |          effectively any other container on the same
postgres_1  |          system.
postgres_1  |
postgres_1  |          Use "-e POSTGRES_PASSWORD=password" to set
postgres_1  |          it in "docker run".
postgres_1  | ****************************************************
postgres_1  | waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
postgres_1  | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
postgres_1  | LOG:  database system was shut down at 2018-03-14 02:02:15 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
postgres_1  |  done
postgres_1  | server started
postgres_1  | ALTER ROLE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | LOG:  shutting down
postgres_1  | waiting for server to shut down....LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2018-03-14 02:02:17 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start /usr/src/app
app_1       | > NODE_ENV=production npm-run-all --parallel start:*
app_1       |
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart:main: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start:main: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start:main /usr/src/app
app_1       | > node server/index.js
app_1       |
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart:consumer: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start:consumer: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start:consumer /usr/src/app
app_1       | > node server/feedback-consumer/consumer.js
app_1       |
app_1       | /usr/src/app/server/models/setting.js:7
app_1       |   throw new Error('AWS encryption password was empty. Set a password by providing the ENCRYPTION_PASSWORD environment variable in .env');
app_1       |   ^
app_1       |
app_1       | Error: AWS encryption password was empty. Set a password by providing the ENCRYPTION_PASSWORD environment variable in .env
app_1       |     at Object.<anonymous> (/usr/src/app/server/models/setting.js:7:9)
app_1       |     at Module._compile (module.js:569:30)
app_1       |     at Object.Module._extensions..js (module.js:580:10)
app_1       |     at Module.load (module.js:503:32)
app_1       |     at tryModuleLoad (module.js:466:12)
app_1       |     at Function.Module._load (module.js:458:3)
app_1       |     at Module.require (module.js:513:17)
app_1       |     at require (internal/module.js:11:18)
app_1       |     at Sequelize.import (/usr/src/app/node_modules/sequelize/lib/sequelize.js:686:61)
app_1       |     at /usr/src/app/server/models/index.js:23:36
app_1       |     at Array.forEach (native)
app_1       |     at Object.<anonymous> (/usr/src/app/server/models/index.js:22:4)
app_1       |     at Module._compile (module.js:569:30)
app_1       |     at Object.Module._extensions..js (module.js:580:10)
app_1       |     at Module.load (module.js:503:32)
app_1       |     at tryModuleLoad (module.js:466:12)
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start:main: Failed to exec start:main script
app_1       | npm ERR! code ELIFECYCLE
app_1       | npm ERR! errno 1
app_1       | npm ERR! nonprofit-email-service@1.0.0 start:main: `node server/index.js`
app_1       | npm ERR! Exit status 1
app_1       | npm ERR!
app_1       | npm ERR! Failed at the nonprofit-email-service@1.0.0 start:main script.
app_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1       |
app_1       | npm ERR! A complete log of this run can be found in:
app_1       | npm ERR!     /root/.npm/_logs/2018-03-14T02_11_09_715Z-debug.log
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~poststart:consumer: nonprofit-email-service@1.0.0
app_1       | npm info ok
app_1       | ERROR: "start:main" exited with 1.
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start: Failed to exec start script
app_1       | npm ERR! code ELIFECYCLE
app_1       | npm ERR! errno 1
app_1       | npm ERR! nonprofit-email-service@1.0.0 start: `NODE_ENV=production npm-run-all --parallel start:*`
app_1       | npm ERR! Exit status 1
app_1       | npm ERR!
app_1       | npm ERR! Failed at the nonprofit-email-service@1.0.0 start script.
app_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1       |
app_1       | npm ERR! A complete log of this run can be found in:
app_1       | npm ERR!     /root/.npm/_logs/2018-03-14T02_11_09_776Z-debug.log
mailforgood_app_1 exited with code 1
```

**Comment by AndrewGHC** [comment]
Hey @darkrubyist - please set a password in your .env file, as in https://github.com/freeCodeCamp/mail-for-good/blob/master/.env.example

**Comment by darkrubyist** [comment]
Thank you very much for your help.
Now seems that Docker is composing and the server is starting, but when I visit the http://localhost:8080, there is no server running:


Here are my logs. Thank you very much again!
```

arkloves-MacBook-Pro% sudo docker-compose up
Starting mailforgood_redis_1 ...
Starting mailforgood_redis_1 ... done
Starting mailforgood_app_1 ... done
Attaching to mailforgood_postgres_1, mailforgood_redis_1, mailforgood_app_1
postgres_1  | LOG:  database system was shut down at 2018-03-16 11:54:51 UTC
redis_1     | 1:C 16 Mar 11:57:15.989 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
redis_1     | 1:C 16 Mar 11:57:15.989 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 16 Mar 11:57:15.990 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1     | 1:M 16 Mar 11:57:15.991 * Running mode=standalone, port=6379.
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
redis_1     | 1:M 16 Mar 11:57:15.992 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 16 Mar 11:57:15.992 # Server initialized
redis_1     | 1:M 16 Mar 11:57:15.994 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 16 Mar 11:57:15.994 * DB loaded from disk: 0.000 seconds
redis_1     | 1:M 16 Mar 11:57:15.995 * Ready to accept connections
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start /usr/src/app
app_1       | > NODE_ENV=production npm-run-all --parallel start:*
app_1       |
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@5.3.0
app_1       | npm info using node@v8.2.1
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart:main: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start:main: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start:main /usr/src/app
app_1       | > node server/index.js
app_1       |
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~prestart:consumer: nonprofit-email-service@1.0.0
app_1       | npm info lifecycle nonprofit-email-service@1.0.0~start:consumer: nonprofit-email-service@1.0.0
app_1       |
app_1       | > nonprofit-email-service@1.0.0 start:consumer /usr/src/app
app_1       | > node server/feedback-consumer/consumer.js
app_1       |
app_1       | Feedback consumer started: watching for feedback messages (bounces, complaints, etc) from SQS
app_1       | (node:53) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | Clickthrough tracking: Make sure that geoip data has been downloaded:
app_1       |    $ cd node_modules/geoip-lite
app_1       |    $ npm run-script updatedb
app_1       |
app_1       |   ############################
app_1       |   #   Mail 4 Good started    #
app_1       |   ############################
app_1       |   # Port: 8080
app_1       |   ############################
app_1       |
app_1       | (node:47) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
```

**Comment by darkrubyist** [comment]
I figure out why it was not working. http://localhost:8080 didn't work but http://localhost did. Thanks for help @AndrewGHC

**Comment by AndrewGHC** [comment]
@darkrubyist Glad you got it working, thanks.
