### ISSUE TITLE
App errors after being installed through Heroku button

### ISSUE THREAD

**Issue by curiousdannii** [freeCodeCamp/mail-for-good#348]
Hi, I'm trying to install this, and while the app seems to install and build correctly using the Heroku button, when the app actually starts I get the following errors:

```
2020-02-04T11:10:59.503608+00:00 heroku[web.1]: State changed from crashed to starting
2020-02-04T11:08:48+00:00 app[heroku-redis]: source=REDIS addon=**** sample#active-connections=1 sample#load-avg-1m=0.165 sample#load-avg-5m=0.14 sample#load-avg-15m=0.16 sample#read-iops=0 sample#write-iops=0.18333 sample#memory-total=15664264kB sample#memory-free=12243228kB sample#memory-cached=1418088kB sample#memory-redis=313944bytes sample#hit-rate=1 sample#evicted-keys=0
2020-02-04T11:11:12.315130+00:00 heroku[web.1]: Starting process with command `npm start`
2020-02-04T11:11:15.829123+00:00 app[web.1]: 
2020-02-04T11:11:15.829139+00:00 app[web.1]: > nonprofit-email-service@1.0.0 start /app
2020-02-04T11:11:15.829141+00:00 app[web.1]: > NODE_ENV=production npm-run-all --parallel start:*
2020-02-04T11:11:15.829143+00:00 app[web.1]: 
2020-02-04T11:11:17.066340+00:00 app[web.1]: 
2020-02-04T11:11:17.066381+00:00 app[web.1]: > nonprofit-email-service@1.0.0 start:main /app
2020-02-04T11:11:17.066385+00:00 app[web.1]: > node server/index.js
2020-02-04T11:11:17.066388+00:00 app[web.1]: 
2020-02-04T11:11:17.195402+00:00 app[web.1]: 
2020-02-04T11:11:17.195406+00:00 app[web.1]: > nonprofit-email-service@1.0.0 start:consumer /app
2020-02-04T11:11:17.195409+00:00 app[web.1]: > node server/feedback-consumer/consumer.js
2020-02-04T11:11:17.195412+00:00 app[web.1]: 
2020-02-04T11:11:18.780087+00:00 app[web.1]: Feedback consumer started: watching for feedback messages (bounces, complaints, etc) from SQS
2020-02-04T11:11:18.889890+00:00 app[web.1]: (node:58) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
2020-02-04T11:11:18.995672+00:00 app[web.1]: Connection has been established successfully.
2020-02-04T11:11:19.005119+00:00 app[web.1]: Unhandled rejection SequelizeBaseError: relation "settings" does not exist
2020-02-04T11:11:19.005123+00:00 app[web.1]:     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
2020-02-04T11:11:19.005125+00:00 app[web.1]:     at Result.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
2020-02-04T11:11:19.005128+00:00 app[web.1]:     at emitOne (events.js:96:13)
2020-02-04T11:11:19.005130+00:00 app[web.1]:     at Result.emit (events.js:189:7)
2020-02-04T11:11:19.005133+00:00 app[web.1]:     at Result.Query.handleError (/app/node_modules/pg/lib/query.js:163:8)
2020-02-04T11:11:19.005135+00:00 app[web.1]:     at Client.<anonymous> (/app/node_modules/pg/lib/client.js:188:26)
2020-02-04T11:11:19.005137+00:00 app[web.1]:     at emitOne (events.js:96:13)
2020-02-04T11:11:19.005140+00:00 app[web.1]:     at Connection.emit (events.js:189:7)
2020-02-04T11:11:19.005142+00:00 app[web.1]:     at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:133:12)
2020-02-04T11:11:19.005144+00:00 app[web.1]:     at emitOne (events.js:96:13)
2020-02-04T11:11:19.005147+00:00 app[web.1]:     at TLSSocket.emit (events.js:189:7)
2020-02-04T11:11:19.005150+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2020-02-04T11:11:19.005152+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:134:10)
2020-02-04T11:11:19.005154+00:00 app[web.1]:     at TLSWrap.onread (net.js:551:20)
2020-02-04T11:11:19.444972+00:00 app[web.1]: Clickthrough tracking: Make sure that geoip data has been downloaded: 
2020-02-04T11:11:19.445964+00:00 app[web.1]:    $ cd node_modules/geoip-lite
2020-02-04T11:11:19.446069+00:00 app[web.1]:    $ npm run-script updatedb
2020-02-04T11:11:19.942374+00:00 app[web.1]: /app/node_modules/ws/lib/websocket.js:347
2020-02-04T11:11:19.942393+00:00 app[web.1]:       ...options
2020-02-04T11:11:19.942396+00:00 app[web.1]:       ^^^
2020-02-04T11:11:19.942398+00:00 app[web.1]: SyntaxError: Unexpected token ...
2020-02-04T11:11:19.942400+00:00 app[web.1]:     at Object.exports.runInThisContext (vm.js:73:16)
2020-02-04T11:11:19.942403+00:00 app[web.1]:     at Module._compile (module.js:543:28)
2020-02-04T11:11:19.942405+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2020-02-04T11:11:19.942408+00:00 app[web.1]:     at Module.load (module.js:488:32)
2020-02-04T11:11:19.942410+00:00 app[web.1]:     at tryModuleLoad (module.js:447:12)
2020-02-04T11:11:19.942415+00:00 app[web.1]:     at Function.Module._load (module.js:439:3)
2020-02-04T11:11:19.942418+00:00 app[web.1]:     at Module.require (module.js:498:17)
2020-02-04T11:11:19.942420+00:00 app[web.1]:     at require (internal/module.js:20:19)
2020-02-04T11:11:19.942422+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/ws/index.js:3:19)
2020-02-04T11:11:19.942425+00:00 app[web.1]:     at Module._compile (module.js:571:32)
2020-02-04T11:11:19.942427+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2020-02-04T11:11:19.942429+00:00 app[web.1]:     at Module.load (module.js:488:32)
2020-02-04T11:11:19.942431+00:00 app[web.1]:     at tryModuleLoad (module.js:447:12)
2020-02-04T11:11:19.942434+00:00 app[web.1]:     at Function.Module._load (module.js:439:3)
2020-02-04T11:11:19.942436+00:00 app[web.1]:     at Module.require (module.js:498:17)
2020-02-04T11:11:19.942438+00:00 app[web.1]:     at require (internal/module.js:20:19)
2020-02-04T11:11:19.977633+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-02-04T11:11:19.978515+00:00 app[web.1]: npm ERR! errno 1
2020-02-04T11:11:19.980530+00:00 app[web.1]: npm ERR! nonprofit-email-service@1.0.0 start:main: `node server/index.js`
2020-02-04T11:11:19.981579+00:00 app[web.1]: npm ERR! Exit status 1
2020-02-04T11:11:19.981582+00:00 app[web.1]: npm ERR! 
2020-02-04T11:11:19.981585+00:00 app[web.1]: npm ERR! Failed at the nonprofit-email-service@1.0.0 start:main script.
2020-02-04T11:11:19.981588+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-02-04T11:11:19.996484+00:00 app[web.1]: 
2020-02-04T11:11:19.997360+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-02-04T11:11:19.998080+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-02-04T11_11_19_984Z-debug.log
2020-02-04T11:11:20.046787+00:00 app[web.1]: ERROR: "start:main" exited with 1.
2020-02-04T11:11:20.059442+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-02-04T11:11:20.060001+00:00 app[web.1]: npm ERR! errno 1
2020-02-04T11:11:20.061243+00:00 app[web.1]: npm ERR! nonprofit-email-service@1.0.0 start: `NODE_ENV=production npm-run-all --parallel start:*`
2020-02-04T11:11:20.061382+00:00 app[web.1]: npm ERR! Exit status 1
2020-02-04T11:11:20.061575+00:00 app[web.1]: npm ERR! 
2020-02-04T11:11:20.061701+00:00 app[web.1]: npm ERR! Failed at the nonprofit-email-service@1.0.0 start script.
2020-02-04T11:11:20.061858+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-02-04T11:11:20.070958+00:00 app[web.1]: 
2020-02-04T11:11:20.071131+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-02-04T11:11:20.071229+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-02-04T11_11_20_063Z-debug.log
2020-02-04T11:11:20.190851+00:00 heroku[web.1]: State changed from starting to crashed
2020-02-04T11:11:20.168607+00:00 heroku[web.1]: Process exited with status 1
```

Looks like possibly three separate issues: something with pg/sequelize, geoip-lite (has this app been updated to handle the [MaxMind changes announced in Dec 2019?](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/)), and a JS syntax error.

**Comment by curiousdannii** [comment]
I got it working by removing the engines section from package.json and bumping bcrypt to 3.0.0.

https://github.com/curiousdannii/mail-for-good/commits/heroku/stable
